#  ref: https://github.com/marketplace/actions/lighthouse-ci-action#example

name: Lighthouse CI
on:
  push:
    branches: [$default-branch, develop]
  pull_request:
    branches: [$default-branch, develop]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://todomvc.pages.dev
            https://develop.todomvc.pages.dev
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
